-- Run this file once in Supabase SQL Editor.

create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  name text not null,
  client_token text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists registrations_name_unique_ci
  on public.registrations (lower(trim(name)));

alter table public.registrations enable row level security;

-- The browser never reads/writes the table directly. All access goes through
-- SECURITY DEFINER RPC functions below, so private client_token values are not exposed.
revoke all on public.registrations from anon, authenticated;

drop function if exists public.get_registrations();
create function public.get_registrations()
returns table(position bigint, name text, created_at timestamptz)
language sql
security definer
set search_path = public
as $$
  select
    row_number() over (order by r.created_at, r.id) as position,
    r.name,
    r.created_at
  from public.registrations r
  order by r.created_at, r.id
  limit 18;
$$;

drop function if exists public.join_event(text, text);
create function public.join_event(p_name text, p_client_token text)
returns table(position bigint, status text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text := trim(p_name);
  v_count integer;
  v_id bigint;
begin
  if v_name is null or char_length(v_name) < 1 or char_length(v_name) > 40 then
    raise exception 'invalid_name';
  end if;
  if p_client_token is null or char_length(trim(p_client_token)) < 12 then
    raise exception 'invalid_token';
  end if;

  -- Serializes sign-up decisions for this one event so two people cannot claim
  -- the same last confirmed slot at the same time.
  perform pg_advisory_xact_lock(982601817);

  if exists (select 1 from public.registrations where lower(trim(name)) = lower(v_name)) then
    raise exception 'already_registered';
  end if;

  select count(*) into v_count from public.registrations;
  if v_count >= 18 then
    raise exception 'signup_full';
  end if;

  insert into public.registrations(name, client_token)
  values (v_name, p_client_token)
  returning id into v_id;

  position := v_count + 1;
  status := case when position <= 12 then 'confirmed' else 'waiting' end;
  return next;
end;
$$;

drop function if exists public.cancel_registration(text, text);
create function public.cancel_registration(p_name text, p_client_token text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_deleted integer;
begin
  perform pg_advisory_xact_lock(982601817);

  delete from public.registrations
  where lower(trim(name)) = lower(trim(p_name))
    and client_token = p_client_token;

  get diagnostics v_deleted = row_count;
  return v_deleted = 1;
end;
$$;

grant execute on function public.get_registrations() to anon, authenticated;
grant execute on function public.join_event(text, text) to anon, authenticated;
grant execute on function public.cancel_registration(text, text) to anon, authenticated;

-- Realtime notification support. If this fails because the table is already in
-- the publication, that is harmless.
do $$
begin
  alter publication supabase_realtime add table public.registrations;
exception
  when duplicate_object then null;
end $$;
